[build]
  publish = "public"
  functions = "functions"

[functions]
  directory = "functions"
  [[functions.scheduled]]
    name = "scheduled-call"
    schedule = "*/1 * * * *"

[[plugins]]
  package = "@netlify/plugin-scheduled-functions"
